import { Geist, Geist_Mono , Oswald } from "next/font/google";
import { Barlow_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";

// Existing fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-oswald',
});

// Add Barlow Condensed
const barlowCondensed = Barlow_Condensed({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-barlow-condensed',
});

export const metadata = {
  title: "New Head Turners",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${barlowCondensed.variable}  ${oswald.variable}  antialiased`}
        style={{
          fontFamily: 'var(--font-oswald)',
          letterSpacing: '0.05em',
        }}
      >
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}